### ISSUE TITLE
Something going on with spells and using /reload and on server start

### ISSUE THREAD

**Issue by itsdinkd** [CammiePone/Arcanus#14]
When using /reload, I cannot complete the reload. I get the message below. I also get this message on server start, without the first line though. 

1.17.1 
Fabric
v1.14 of arcanus

[19:55:04] [Server thread/WARN] (class_3097) Failed to execute reload
 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Class dev.cammiescorner.arcanus.core.registry.ModCommands$SpellArgumentType already has a serializer!
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1190) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2305) ~[?:?]
        at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1334) ~[intermediary-server.jar:?]
        at net.minecraft.class_3097.method_29480(class_3097.java:22) ~[intermediary-server.jar:?]
        at net.minecraft.class_3097.method_13530(class_3097.java:53) ~[intermediary-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.redirect$zbb000$performCommand(class_2170.java:547) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:363) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:336) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$dcn000$modifiedRunLoop(MinecraftServer.java:9390) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Class dev.cammiescorner.arcanus.core.registry.ModCommands$SpellArgumentType already has a serializer!
        at net.minecraft.class_2316.method_10017(class_2316.java:74) ~[intermediary-server.jar:?]
        at dev.cammiescorner.arcanus.core.registry.ModCommands.init(ModCommands.java:33) ~[arcanus-1.14.jar:?]
        at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[8424afa7-0e20-480c-b0e2-39776187a836.jar:?]
        at net.minecraft.class_2170.handler$zgf000$fabric_addCommands(class_2170.java:1547) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:235) ~[intermediary-server.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:39) ~[intermediary-server.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29437(MinecraftServer.java:1335) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        ... 14 more
[19:55:04] [Server thread/INFO] (MinecraftServer) Reload failed; keeping old data

**Comment by CammiePone** [comment]
mmm fun, I knew that would bite me in the ass later.

commands suck

**Comment by itsdinkd** [comment]
:/

**Comment by itsdinkd** [comment]
is this preventing new data from being written?

**Comment by CammiePone** [comment]
Not sure. I knew commands would come back and bite me, just didnt know how or when. I'll have to poke Upcraft when he's awake about this

**Comment by itsdinkd** [comment]
Would disabling the mod on my server/modpack until fix be the appropriate thing to do for now?

**Comment by CammiePone** [comment]
Probably not since the next update will take a while, as it'll be the infamous 2.0 update

**Comment by itsdinkd** [comment]
hmm.. if its restricting data from writing though or reloading it might not be the best idea to leave running.

THE FEELS :*( i loved this mod too :(

**Comment by CammiePone** [comment]
See about updating to 1.15

I dont think it'll matter, but give it a go

**Comment by itsdinkd** [comment]
Updated to 1.15, client looks fine, going to try server.

Btw,

Lookie what I found in my client logs


[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:legs/belt as it is missing farcanus:belt_of_the_rabbit (from Arcanus),arcanus:belt_of_rejuvenation (from Arcanus)
[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:hand/glove as it is missing following references: arcanus:gloves_of_disengagement (from Arcanus)
[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:offhand/glove as it is missing following references: #trinkets:hand/glove (from Arcanus)
[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:hand/ring as it is missing following references: arcanus:ring_of_shielding (from Arcanus),arcanus:ring_of_the_enderman (from Arcanus),arcanus:ring_of_the_monk (from Arcanus),arcanus:ring_of_the_west_wind (from Arcanus)
[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:offhand/ring as it is missing following references: #trinkets:hand/ring (from Arcanus)
[18:00:35] [Worker-Main-31/ERROR]: Couldn't load tag trinkets:chest/necklace as it is missing following references: arcanus:amulet_of_soothing (from Arcanus),arcanus:amulet_of_purging (from Arcanus),arcanus:amulet_of_the_master (from Arcanus)

**Comment by itsdinkd** [comment]
yeah i still get it on the server.

**Comment by CammiePone** [comment]
Upcraft has come through ~~after I forgot to ask him for a week sorry about that~~ so there should be a fix going out soon
