### ISSUE TITLE
Crash on Newest Version of Fabric

### ISSUE THREAD

**Issue by yahi-ko** [CammiePone/Arcanus#20]
Crash on Fabric 0.12.1
Minecraft Version: 1.17.1

Mods: 
Cloth Config 5.0.38
Arcanus 1.16
Trinkets 3.0.4
Fabric API 0.40.8

Arcanus 1.16 only works currently on Fabric 0.11.7

**Comment by yahi-ko** [comment]
[14:06:34] [main/INFO]: Compatibility level set to JAVA_16
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Minecraft has crashed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2246.<clinit>(class_2246.java:103)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 35 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method damage(FLnet/minecraft/class_1282;)F in arcanus.mixins.json:LivingEntityMixin from mod arcanus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap arcanus-refmap.json Messages: { @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 577 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 619 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 620 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 625 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 629 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 638 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 656 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required. @At("LOAD" implicit float) has invalid IMPLICIT discriminator for opcode 657 in net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z: Found 3 candidate variables but exactly 1 is required.}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 38 more
Exiting with -1
Process exited with code -1.

**Comment by UpcraftLP** [comment]
Yep.. fabric loader 0.12 ships a newer version of the mixin library, which seems to break the way arcanus is doing things.

I'm currently working on a fix for this
