### ISSUE TITLE
Crash when spectating any entity

### ISSUE THREAD

**Issue by campbellcole** [CammiePone/Arcanus#25]
My save is currently unplayable because I am in a stronghold and every time I join the save the game instantly crashes before rendering a frame. The stacktrace starts with a method within this mod, so I am assuming this mod is causing it. I am using the Valhelsia Fabric modpack, so if you're sure this isn't a problem with your mod, I'll go to them.

Stacktrace:
```
java.lang.ClassCastException: class net.minecraft.class_1613 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1613 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at dev.cammiescorner.arcanus.core.util.EventHandler.lambda$clientEvents$0(EventHandler.java:51)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zip000$render(class_329.java:2993)
	at net.minecraft.class_329.method_1753(class_329.java:405)
	at net.minecraft.class_757.method_3192(class_757.java:855)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

I was in spectator mode when the game crashed, so that may have something to do with it seeing as it's mentioning HUD rendering. I was trying to find a library, and I did, but the game didn't crash because I was in the library. I was in a wall relatively far away from the library when it happened, so I don't think it's loot chest issues. You know best, though. Thanks for your time.

**Comment by CammiePone** [comment]
It's trying to cast SkeletonEntity to PlayerEntity for some ungodly reason in a HUD renderer, so I guess I'll look into it tomorrow morning. Im going to bed for rn

**Comment by CammiePone** [comment]
Oh, are you speculating a skeleton right now?

**Comment by CammiePone** [comment]
Spectating, Fuck you autocorrect

**Comment by campbellcole** [comment]
I manually mapped the two classes and this is what I found, it definitely is a problem with this mod:
`Intermediary` -> `Mojang Mapped` -> `Mojang Unmapped`
`class_1613` -> `big` -> `net.minecraft.world.entity.monster.Skeleton`
`class_1657` -> `bke` -> `net.minecraft.world.entity.player.Player`

I believe I must've accidentally started spectating a skeleton, which set the `client.cameraEntity` to a Skeleton, causing this crash. If I did not accidentally spectate a skeleton, the error still makes some sense, though I'm not sure what other situation would cause the client camera to become a skeleton.

Edit: Oops, didn't see you'd responded. We've arrived at the same conclusion which is good. I said it above, but I didn't mean to spectate a skeleton if I am so I'm not 100% sure, but it seems like that must be the case.

**Comment by CammiePone** [comment]
Question: can you log into the world but tab out of the game before you load in and see if it lets you change the difficulty that way? May unsoftlock you

**Comment by campbellcole** [comment]
I'll try that now, excellent idea.

**Comment by campbellcole** [comment]
Yep! That worked perfectly, and I definitely was spectating a skeleton. Thanks so much.

**Comment by CammiePone** [comment]
Okay cool, glad it wasnt a true softlock! I'll try and fix it tomorrow
