### ISSUE TITLE
Mana Flask predicate borked

### ISSUE THREAD

**Issue by wootaboot** [CammiePone/Arcanus#3]
Time: 2021-08-22, 12:06 p.m.
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10550(String)" because the return value of "net.minecraft.class_1799.method_7941(String)" is null
	at dev.cammiescorner.arcanus.client.ArcanusClient.lambda$itemPredicateRegistry$1(ArcanusClient.java:67)
	at net.minecraft.class_6395.call(class_6395.java:14)
	at net.minecraft.class_806.method_3495(class_806.java:144)
	at net.minecraft.class_918.method_4019(class_918.java:390)
	at net.minecraft.class_918.method_4026(class_918.java:493)
	at net.minecraft.class_918.method_36543(class_918.java:486)
	at net.minecraft.class_918.method_27953(class_918.java:476)
	at badasintended.megane.runtime.util.RuntimeUtils.drawStack(RuntimeUtils.java:108)
	at badasintended.megane.runtime.renderer.InventoryRenderer.draw(InventoryRenderer.java:72)
	at mcp.mobius.waila.util.DrawableText.render(DrawableText.java:56)
	at mcp.mobius.waila.hud.HudRenderer.render(HudRenderer.java:216)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zgf000$render(class_329.java:2493)
	at net.minecraft.class_329.method_1753(class_329.java:439)
	at net.minecraft.class_757.method_3192(class_757.java:1214)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by wootaboot** [comment]
Crashed after dreamwarp to death, was blown up by creeper after respawning and it crashed.

**Comment by CammiePone** [comment]
So fun fact, it's actually crashing on the predicate for the Mana Flask. I got lazy and didn't bother with a check so that's on me.
